name: emmet
description: A test documentation generator for Dart/Flutter projects
version: 0.0.1+2
author: Apparence.io
homepage: https://github.com/Apparence-io/emmet

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4  

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

