name: emmet
description: A test documentation generator for Dart/Flutter projects
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.1.0
  json_annotation: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4 
  build_runner: ^1.11.5
  json_serializable: ^4.0.2


# dev_dependencies:
#   flutter_test:
#     sdk: flutter

